[package]
authors = ["Fabio Zahner"]
categories = ["office"]
description = "Generate simple invoices with swiss payment QR code."
disciplines = ["business"]
entrypoint = "invoice-maker.typ"
exclude = ["*.pdf"]
keywords = ["invoice", "accounting", "finance", "money"]
license = "ISC"
name = "invoice-maker"
repository = "https://github.com/fzahner/simple-swiss-invoice"
version = "1.0.0"

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "images/main.png"
